### ISSUE TITLE
聊天过程中，输入问题后，希望加入回车发送问题

### ISSUE THREAD

**Issue by abpyu** [Ai00-X/ai00_server#102]
在输入问题时，按回车是换行，不是发送
输入问题后，需要鼠标点击发送，才会将问题发送给后台
希望增加配置文件设置选项，回车=换行/发送
<img width="768" alt="F70A75B0C058976F2BD288DCA92656D2" src="https://github.com/Ai00-X/ai00_server/assets/17792840/6636ab9e-afd9-4b74-9ca4-5743f74d8783">

**Comment by cryscan** [comment]
可以输入 Shift + Enter 发送消息。
