### ISSUE TITLE
2 bugs in mirostat sampler

### ISSUE THREAD

**Issue by cahya-wirawan** [Ai00-X/ai00_server#105]
Hi,

1. The first bug is in the function estimate_s. The function is unstable because the probability in denominator could be 0.0. As result, num below become NaN.

<img width="785" alt="Screenshot 2024-04-20 at 16 04 23" src="https://github.com/Ai00-X/ai00_server/assets/7669893/ad43a974-0e6e-49e2-a168-a46c95dccdae">

2. The second bug is in the function compute_k. This function is very unstable, the result is overflow.
<img width="1146" alt="Screenshot 2024-04-20 at 18 26 04" src="https://github.com/Ai00-X/ai00_server/assets/7669893/34675211-72d8-40a3-9878-72e9a66912d6">

- n.powf(-eps) = 1 / n.powf(eps) -> for n=65536, it can become overflow easily
- powf(1.0 / s) -> s can become 0.0 -> unstable.

A plot of the formula **k = (eps * 2.0_f32.powf(tau) / (1.0 - n.powf(-eps))).powf(1.0 / s)** using wolframalpha show its stability:
<img width="794" alt="Screenshot 2024-04-20 at 18 17 15" src="https://github.com/Ai00-X/ai00_server/assets/7669893/e7f0e4d9-4de0-4836-a3b5-e4ef5a130151">

**Comment by cryscan** [comment]
The power in the formula is n^(-eps) so it should be 65536^(1-x), and this is what I get:
![0dfe9c2e2e77fe3837a0999ba6f61300](https://github.com/Ai00-X/ai00_server/assets/16053640/51ef0190-1591-4197-9c69-c78f5fa1f263)

**Comment by cryscan** [comment]
Just pushed a fix. would you like to try again?

**Comment by cahya-wirawan** [comment]
yes, may bad, I overlook -eps. I tried the fix, it runs now without overflow so far. However, the formula is in my opinion  unstable because k is undefined for s==1.0 and s==0. k is also huge or overflow for -0.5<s<0.
<img width="463" alt="Screenshot 2024-04-21 at 15 54 37" src="https://github.com/Ai00-X/ai00_server/assets/7669893/7298e32f-f1ed-4001-a0f1-a88312910c94">
