### ISSUE TITLE
Higher number of Num Tokens?

### ISSUE THREAD

**Issue by hypnopump** [Ai00-X/ai00_server#134]
Hi, I would like to inference a higher number for Num Tokens, potentially 100K-1M. 

Can that be enabled in the GUI? 

Otherwise, could you point me to the UI code (not the minimized JS under the `assets/www/index.zip`) so i can modify myself?

Thanks~

**Comment by cryscan** [comment]
@cgisky1980

**Comment by cryscan** [comment]
Actually the prefill speed would like to be maxed at about 256. Higher than that does not worth it.

**Comment by hypnopump** [comment]
hmm i think if you give a long enough prompt (>8k) it just freezes. Never returns anything, but the GPU memory is not maxed out, it just refuses the request

**Comment by cryscan** [comment]
I see. There is a limit in the backend for a single request which is 4k. I can remove it anyway.

**Comment by hypnopump** [comment]
yes please, or at least make it configurable in via the yaml config file=

**Comment by cryscan** [comment]
The limit has been removed.
