### ISSUE TITLE
ubuntu 24.04 load runtime failed: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by Alic-Li** [Ai00-X/ai00_server#143]
alic-li@alic-li-B660M-D2H-DDR4:~/ai00$ ./ai00-server 
2024-09-09T08:17:44.881Z INFO  [ai00_server] ai00_server	version: 0.5.7
2024-09-09T08:17:44.881Z INFO  [ai00_server] reading config assets/configs/Config.toml...
tokenizer.json [00:00:02] [████████████████] 16.29 MiB/16.29 MiB 7.35 MiB/s (0s)2024-09-09T08:17:48.653Z INFO  [ai00_server] loading embed model: intfloat/multilingual-e5-small
onnx/model.onnx [00:00:42] [████████████] 448.48 MiB/448.48 MiB 10.60 MiB/s (0s)config.json [00:00:00] [█████████████████████████████] 655 B/655 B 1015 B/s (0s)special_tokens_map.json [00:00:00] [██████████████████] 167 B/167 B 214 B/s (0s)tokenizer_config.json [00:00:00] [████████████████████] 443 B/443 B 638 B/s (0s)2024-09-09T08:18:37.667Z ERROR [ai00_core] load runtime failed: No such file or directory (os error 2)
2024-09-09T08:18:37.701Z INFO  [ai00_server] visit WebUI at http://localhost:65530
2024-09-09T08:18:37.701Z INFO  [ai00_server] server started at 0.0.0.0:65530 without tls
2024-09-09T08:19:15.025Z ERROR [ai00_core] load runtime failed: No such device (os error 19)

修改模型路径后也还是一样的报错，但是奇怪的是我笔记本的22.04是好的，核显也是可以用vulkan正常运行的，进入web UI后可以认设备
VK_LAYER_INTEL_nullhw (INTEL NULL HW) Vulkan version 1.1.73, layer version 1:
	Layer Extensions: count = 0
	Devices: count = 3
		GPU id = 0 (AMD Radeon PRO W7900 (RADV NAVI31))
		Layer-Device Extensions: count = 0

		GPU id = 1 (Intel(R) UHD Graphics 730 (ADL-S GT1))
		Layer-Device Extensions: count = 0

		GPU id = 2 (llvmpipe (LLVM 17.0.6, 256 bits))
                Layer-Device Extensions: count = 0
![截图 2024-09-09 16-30-34](https://github.com/user-attachments/assets/436bda27-f515-495a-a23b-f23b3e27e8c2)
模型路径下的模型认不出来
把模型直接塞在assets/models下也无效

**Comment by cgisky1980** [comment]
config 贴出来看看

**Comment by cgisky1980** [comment]
用0.5.8版本试试

**Comment by Alic-Li** [comment]
好的，晚上回寝室试试看，我们叼毛大一新生还要军训😂

**Comment by Alic-Li** [comment]
> 用0.5.8版本试试

还是一样的😂我又一个朋友用的manjaro也遇到了同样的问题
![image](https://github.com/user-attachments/assets/1cf5828f-8431-4d9e-9911-cccf10fa62b1)
![image](https://github.com/user-attachments/assets/5a0ba857-7186-4e2c-9bd6-18ca4b7d397c)

**Comment by Alic-Li** [comment]
### config是默认的我重新试了一下，没动过
[model]
embed_device = "Cpu"                                 # Device to put the embed tensor ("Cpu" or "Gpu").
max_batch = 8                                        # The maximum batches that are cached on GPU.
name = "RWKV-x060-World-3B-v2.1-20240417-ctx4096.st" # Name of the model.
path = "assets/models"                               # Path to the folder containing all models.
precision = "Fp16"                                   # Precision for intermediate tensors ("Fp16" or "Fp32"). "Fp32" yields better outputs but slower.
quant = 0                                            # Layers to be quantized.
quant_type = "Int8"                                  # Quantization type ("Int8" or "NF4").
stop = ["\n\n"]                                      # Additional stop words in generation.
token_chunk_size = 128                               # Size of token chunk that is inferred at once. For high end GPUs, this could be 64 or 128 (faster).

# [[state]] # State-tuned initial state.
# id = "fd7a60ed-7807-449f-8256-bccae3246222"                      # UUID for this state, which is used to specify which one to use in the APIs.
# name = "x060-3B"                                                 # Given name for this state (optional).
# path = "rwkv-x060-chn_single_round_qa-3B-20240505-ctx1024.state"

# [[state]] # Load another initial state.
# id = "6a9c60a4-0f4c-40b1-a31f-987f73e20315"                      # UUID for this state.
# path = "rwkv-x060-chn_single_round_qa-3B-20240502-ctx1024.state"

# [[lora]] # LoRA and blend factors.
# alpha = 192
# path = "assets/models/rwkv-x060-3b.lora"

[tokenizer]
path = "assets/tokenizer/rwkv_vocab_v20230424.json" # Path to the tokenizer.

[bnf]
enable_bytes_cache = true   # Enable the cache that accelerates the expansion of certain short schemas.
start_nonterminal = "start" # The initial nonterminal of the BNF schemas.

[adapter]
Auto = {} # Choose the best GPU.
# Manual = 0 # Manually specify which GPU to use.

[listen]
acme = false
domain = "local"
ip = "0.0.0.0"   # Use IpV4.
# ip = "::"        # Use IpV6.
force_pass = true
port = 65530
slot = "permisionkey"
tls = false

[[listen.app_keys]] # Allow mutiple app keys.
app_id = "admin"
secret_key = "ai00_is_good"

[web] # Remove this to disable WebUI.
path = "assets/www/index.zip" # Path to the WebUI.

[embed] # Enable embed model, which is based on fast-embedding onnx models.
endpoint = "https://hf-mirror.com"
home = "assets/models/hf"
lib = "assets/ort/onnxruntime.dll"  # Only used under windows.
name = { MultilingualE5Small = {} }

**Comment by No-22-Github** [comment]
同样遇到报错，0.5.8版本
```
./ai00-server 
2024-10-05T10:29:49.249Z INFO  [ai00_server] ai00_server        version: 0.5.8
2024-10-05T10:29:49.249Z INFO  [ai00_server] reading config assets/configs/Config.toml...
tokenizer.json [00:00:01] [████████████████████████████████████████████████████████████] 16.29 MiB/16.29 MiB 9.50 MiB/s (0s)2024-10-05T10:29:52.526Z INFO  [ai00_server] loading embed model: intfloat/multilingual-e5-small
onnx/model.onnx [00:00:43] [████████████████████████████████████████████████████████] 448.48 MiB/448.48 MiB 10.31 MiB/s (0s)config.json [00:00:00] [███████████████████████████████████████████████████████████████████████] 655 B/655 B 2.51 KiB/s (0s)special_tokens_map.json [00:00:00] [██████████████████████████████████████████████████████████████] 167 B/167 B 647 B/s (0s)tokenizer_config.json [00:00:00] [█████████████████████████████████████████████████████████████] 443 B/443 B 1.71 KiB/s (0s)2024-10-05T10:30:40.123Z ERROR [ai00_core] load runtime failed: No such file or directory (os error 2)
2024-10-05T10:30:40.179Z INFO  [ai00_server] visit WebUI at http://localhost:65530
2024-10-05T10:30:40.179Z INFO  [ai00_server] server started at 0.0.0.0:65530 without tls
```
但是没有影响运行，甚至我的A卡和N卡都能用。我没有改配置文件，保持默认。

**Comment by Alic-Li** [comment]
报错依然有，但是实测可以用，能跑就行😋
![image](https://github.com/user-attachments/assets/58596102-510a-4c3d-88b3-938b092a32fd)
