### ISSUE TITLE
v0.3 前后端需求汇总

### ISSUE THREAD

**Issue by cryscan** [Ai00-X/ai00_server#40]
目前 Batch Inference 的后台已经基本可用，现在将新版本前端的需求汇总如下。
注：因为前端模型载入未完成，暂时请使用
```bash
$ cargo r -r -- --model Config.toml
```
启动服务器，并修改`Config.toml`来修改载入配置。

## 添加载入模型功能
向 `/load` 发送 POST，内容如下：
```rust
#[derive(Debug, Deserialize)]
pub struct ReloadRequest {
    /// Path to the model.
    pub path: PathBuf,
    /// Specify layers that needs to be quantized.
    pub quant: Vec<usize>,
    /// Maximum tokens to be processed in parallel at once.
    pub token_chunk_size: usize,
    /// The chunk size for each split of the head matrix.
    pub head_chunk_size: usize,
    /// Maximum number of batches that are active at once.
    pub max_runtime_batch: usize,
    /// Number of states that are cached on GPU.
    pub max_batch: usize,
    /// the (reversed) number of layer at which the output is as embedding.
    pub embed_layer: usize,
}
```

## 向 Sampler 添加 Penalty Decay
新的 Sampler 结构如下：
```rust
#[derive(Debug, Clone)]
pub struct Sampler {
    pub top_p: f32,
    pub temperature: f32,
    pub presence_penalty: f32,
    pub frequency_penalty: f32,
    pub penalty_decay: f32,
}
```

`penalty_decay` 的默认值可设 0.95。

## 解决在推理时无法切换 Chat 的问题
目前在推理未完成时无法切换聊天窗口。目前只能开多个标签页并行测试。

**Comment by cgisky1980** [comment]
好 我回来了

**Comment by cgisky1980** [comment]
@cryscan    前端目前需要的接口汇总
🚸*Fix   /models  接口，返回更多信息，目前这个接口不正常返回信息。
1.  模型的运行状态：是否加载成功
2. /load 提交的参数
3. 模型型号等信息

☢*Add /state   新增端口需求
1. CPU、GPU、内存占用、显存占用、最大内存、最大显存 ……等等信息
2. 模型相关信息（比 /models简单，需要是否运行、模型型号信息）
3. SSE方式每0.5秒推送一次
4. 可以考虑和 /models 合并

☢*Add /listfiles   新增端口需求
1. Post 一个 assets 下的目录名，返回目录下的文件列表 （可指定扩展名，默认返回所有文件）
2. Config.toml 移入 assets/configs 目录
3. www.zip 移入 assets/www目录

☢*Add /download  新增端口需求
1. Post 一个数组  urls，包含下载文件的url、需要保存的目录 （绝对目录和相对目录）、需要保存的文件名
2. Config.toml 移入 assets/configs 目录
3. www.zip 移入 assets/www目录

**Comment by cryscan** [comment]
`Config.toml`已移动至`assets`目录下。注意，启动项`--model`已经改为`--config`。

**Comment by cgisky1980** [comment]
@cryscan   更新了一下 需求描述 和进度，  新增了 一两个API接口需求

**Comment by cryscan** [comment]
1. 界面截图功能无法使用。
2. Prompt最好改成：
  ```
  User: Hi.
  
  Assistant: Hello! I'm your AI assistant. I'm here to help you with various tasks, such as answering questions, brainstorming ideas, drafting emails, writing code, providing advice, and much more.
  
  User: What's the date today?
  
  Assistant: It's ...
  ```
3. 请不要取随机生成的名字。十分违和而且没有用。
4. 设置里面的`max_runtime_batch`和`max_batch`失效。
