### ISSUE TITLE
1.76环境ubuntu编译报错

### ISSUE THREAD

**Issue by phpk** [Ai00-X/ai00_server#75]
`error[E0382]: use of moved value: `app`
   --> src/salvo_main.rs:226:56
    |
138 |     let app = app
    |         --- move occurs because `app` has type `Router`, which does not implement the `Copy` trait
...
145 |         let service = Service::new(app)
    |                                    --- value moved here
...
226 |             salvo::server::Server::new(acceptor).serve(app).await;
    |                                                        ^^^ value used here after move

For more information about this error, try `rustc --explain E0382`.
error: could not compile `ai00_server` (bin "ai00_server") due to 1 previous error`

**Comment by phpk** [comment]
cargo --version
cargo 1.76.0 (c84b36747 2024-01-18)

**Comment by cryscan** [comment]
Please update your repo to the latest.
