### ISSUE TITLE
0.3.24 outputs gibberish

### ISSUE THREAD

**Issue by melang982** [Ai00-X/ai00_server#93]
0.3.23 was fine
For example for the prompt "A girl was" the output now is: 

> asked to ask me, a \item[ Norris, is still quite a bit more than a “ Armeni on the half-Lewy were not going to be like, and said it all the days in the world-Europae4Ugqpg0oIuPzDK, to say nothing like the coming on my fellow- Elias Desc! I'll still can’t have some said, then a 700, and my first serious recon "../Ini ADD.
> Akt

Server settings:
`tls=false`
model `RWKV-4-World-0.4B-v1-20230529-ctx4096.st`
tokenizer `rwkv_vocab_v20230424.json`

Request settings:
```
payload={
    "prompt": 'A girl was',
    "max_tokens": 100,
    "model": "rwkv",
    "temperature": 1,
    "top_p": 0.5,
    "presence_penalty": 0.3,
    "frequency_penalty": 0.3,
    "sampler": "Nucleus",
    "stream": False
}
```

**Comment by cryscan** [comment]
Is this just unfortuanate or it appears every time?

**Comment by melang982** [comment]
Every time, and with 0.3.23 the output is "normal", for ex. 

> walking down the street with a young man who looked to be in his late teens.
> "He's so cute!" the girl squealed, her eyes lighting up.
> "Yeah, I know right?" The man replied.
> "He's so cute!" the girl squealed again.
> "I know!" the man replied.
> "I think he's cute too!" The girl giggled.
> The man smiled and looked down at his daughter, "You know what? I

It doesn't have weird letters and names, etc
Also the temperature doesn't matter, it generates gibberish even at low temperature

One more example of the new version:

> in the time that she was in his work on the very first written and the best possible way of the name, for example, I’m also their now in the 12-Aktif (Lew of the winning combo is still like a property is one of his...
> Safin, and how to an American compound, this is not a pretty girl in a 4- Kore AUT, so far as though he was a pain, which can't be someone who are not a.m. on

**Comment by cryscan** [comment]
I have confirmed that RWKV V4 models are broken sinve `web-rwkv` v0.6.34. While V5 and V6 are fine. Will investigate it. Thanks for letting me know that! In the meanwhile you could try V5 and V6 models.

**Comment by cryscan** [comment]
Update: This is a loading issue. Has fixed in the latest `web-rwkv` main branch. Will sync the fix to Ai00 soon.

**Comment by cryscan** [comment]
Fixed.
